// This file was auto-generated by tauri-codegen
// Do not edit this file manually

export interface User {
  id: number;
  name: string;
  email: string | null;
}

export interface CreateUserRequest {
  name: string;
  email: string | null;
}

export type Status = "Active" | "Inactive" | "Pending";

