// This file was auto-generated by tauri-codegen
// Do not edit this file manually

import { invoke } from "@tauri-apps/api/core";
import type { User, CreateUserRequest } from "./types";

export async function greet(name: string): Promise<string> {
  return invoke<string>("greet", { name });
}

export async function getUser(id: number): Promise<User> {
  return invoke<User>("get_user", { id });
}

export async function createUser(request: CreateUserRequest): Promise<User> {
  return invoke<User>("create_user", { request });
}

export async function getAllUsers(): Promise<User[]> {
  return invoke<User[]>("get_all_users");
}

export async function deleteUser(id: number): Promise<void> {
  return invoke<void>("delete_user", { id });
}

